// ── Shared COA requirement labels + interpretive guidance ─────────────────────
// Source: COA Guidelines for Counting Clinical Experiences, January 2026
// Format: (minimum) [preferred/recommended]

export interface CoaRequirementMeta {
  label: string;
  guidance: string;
  /** Minimum count required by COA. 0 means tracked but no enforced minimum. */
  minRequired: number;
  /**
   * COA recommended/preferred target (from the January 2026 Guidelines brackets).
   * Undefined means no recommended target listed.
   */
  recommended?: number;
  simulationAllowed?: boolean;
}

export const COA_META: Record<string, CoaRequirementMeta> = {
  'coa.hour.clinical_total':                          { minRequired: 2000, label: 'Total Clinical Hours', guidance: 'Clinical hours include time spent in the actual administration of anesthesia (anesthesia time) and other time spent in the clinical area. Total clinical hours are inclusive of total hours of anesthesia time; therefore, this number must be equal to or greater than the total number of hours of anesthesia time. Other clinical time includes in-house call, preanesthesia assessment, postanesthesia assessment, patient preparation, OR preparation, and time spent participating in clinical rounds.' },
  'coa.case.anesthesia.hours':                        { minRequired: 0,    label: 'Anesthesia Hours', guidance: 'Anesthesia time is the time spent by the student directly administering anesthesia care to the patient. It is a subset of total clinical hours.' },
  'coa.assessment.preanesthetic_initial':             { minRequired: 50,   recommended: 100, label: 'Initial Preanesthetic Assessment', guidance: 'The initial preanesthetic assessment is one in which the student personally conducts the assessment by reviewing the patient\'s medical history, conducting an anesthesia-focused physical assessment, and evaluating pertinent laboratory findings/diagnostic testing. This is an original assessment, not a review of or reference to a preanesthetic assessment previously conducted by another anesthesia provider. Clinical experiences cannot be obtained by simulation alone. Minimum 50 required; preferred 100.' },
  'coa.assessment.postanesthetic':                    { minRequired: 50,   recommended: 150, label: 'Postanesthetic Assessment', guidance: 'A postanesthetic assessment is the review by the learner of pertinent patient data for the evaluation of anesthesia outcomes. This may occur anytime during the post-operative/procedural period. The learner informs clinical preceptors of needed interventions or makes appropriate referrals. Documentation may be solely the student case log. The postanesthetic assessment can be accomplished telephonically. Clinical experiences cannot be obtained by simulation. Minimum 50 required; preferred 150.' },
  'coa.assessment.comprehensive_hp':                 { minRequired: 0,    simulationAllowed: true,  label: 'Comprehensive H&P', guidance: 'Comprehensive history and physical assessment includes the history, physical, and psychological assessment of signs and symptoms, pathophysiologic changes, and psychosocial variations of a patient. This experience can be obtained by simulation alone. A preanesthetic assessment is not a comprehensive history and physical.' },
  'coa.assessment.comprehensive_hp.actual':           { minRequired: 0,    label: 'Comprehensive H&P – Actual', guidance: 'A comprehensive history and physical performed on an actual patient. Often required by facilities for patients presenting for surgery or a procedure.' },
  'coa.assessment.comprehensive_hp.simulated':        { minRequired: 0,    simulationAllowed: true,  label: 'Comprehensive H&P – Simulated', guidance: 'A comprehensive history and physical performed in a simulation environment. This experience can be obtained by simulation alone.' },
  'coa.skill.airway.chest_xray':                     { minRequired: 5,    recommended: 10,  simulationAllowed: true, label: 'Chest X-Ray Assessment', guidance: 'The student accurately recognizes normal and abnormal findings on chest x-rays that may have immediate perianesthetic implications (e.g., pneumothorax, pulmonary edema) along with evaluating proper positioning of various tubes and invasive vascular access lines. One "case" = evaluation of one chest x-ray reviewed by a qualified anesthesia provider. The source can be a current or past patient or from an institutional or commercial library. Minimum 5 required; preferred 10.' },
  'coa.case.total':                                   { minRequired: 700,  recommended: 750, label: 'Total Anesthetic Cases', guidance: 'Students can only take credit for a case where they personally provide anesthesia for critical portions of the case. Students cannot take credit for an anesthetic case in which they observe another anesthesia provider manage a patient\'s anesthetic care. Minimum 700 required; preferred 750.' },
  'coa.case.anesthesia.total':                        { minRequired: 700,  recommended: 750, label: 'Anesthesia Cases Total', guidance: 'Total anesthesia cases administered by the student. Minimum 700 required; preferred 750.' },
  'coa.case.emergency':                               { minRequired: 30,   recommended: 50,  label: 'Trauma / Emergency Cases', guidance: 'An emergency case allows the student the opportunity to provide anesthesia under one or more of the following conditions: (1) urgency/continued threat to patient well-being; (2) fewer resources available than during regular operating hours; (3) limited assessment and planning time for the unscheduled case. When a case is deemed an emergency based on the professional opinion of the operating practitioner (surgeon, proceduralist), it may be counted as an emergency case. Minimum 30 required; preferred 50.' },
  'coa.case.pain_management_encounter':               { minRequired: 15,   recommended: 50,  label: 'Pain Management Encounters', guidance: 'Pain management encounters are individual one-on-one patient interactions for the express purpose of intervening in an acute pain episode or a chronic pain condition. Must include a patient assessment prior to initiating a therapeutic action. Examples: initiation of epidural or intrathecal analgesia, patient controlled analgesia, regional analgesia for post-operative pain, adjustment of existing PCA/PCEA, pharmacologic management of acute pain in PACU, trigger point injections, electrical nerve stimulation. The administration of regional anesthesia as the primary anesthetic technique for a surgical procedure does NOT constitute a pain management encounter. Minimum 15 required; preferred 50.' },
  'coa.case.emergence':                               { minRequired: 300,  label: 'Emergence from Anesthesia', guidance: 'The student manages the patient\'s emergence from the anesthetic, including return of protective airway reflexes and return to consciousness. Minimum 300 required.' },
  'coa.case.anesthesia.general':                      { minRequired: 400,  label: 'General Anesthesia', guidance: 'General anesthesia is a drug-induced loss of consciousness during which patients are not arousable, even by painful stimulation. The ability to independently maintain ventilatory function is often impaired. Patients often require assistance in maintaining a patent airway, and positive pressure ventilation may be required. Minimum 400 required.' },
  'coa.case.anesthesia.general_induction_independent':{ minRequired: 50,   recommended: 100, label: 'General Anesthetic – Independent Induction', guidance: 'The student conducts a general anesthetic induction including applying standard monitoring, preoxygenating, selecting and administering induction medications, and managing the airway and ventilation with minimal or no assistance from the supervising CRNA or physician anesthesiologist. "Minimal" assistance = limited verbal advice or reinforcement. The plan of care is always approved by the supervising provider. Minimum 50 required; preferred 100.' },
  'coa.skill.airway.inhalation_induction':            { minRequired: 25,   recommended: 40,  label: 'Inhalation Induction', guidance: 'Inhalation induction using volatile anesthetic agents as the primary method of inducing general anesthesia, typically used in pediatric patients or adults with difficult IV access. Minimum 25 required; preferred 40.' },
  'coa.case.anesthesia.moderate_deep_sedation':       { minRequired: 25,   recommended: 50,  label: 'Moderate / Deep Sedation', guidance: '"Monitored Anesthesia Care" is not synonymous with moderate/deep sedation. Moderate sedation: drug-induced depression of consciousness during which patients respond purposefully to verbal commands. No interventions required to maintain patent airway. Deep sedation: patients cannot be easily aroused, but respond purposefully following repeated or painful stimulation. Minimum 25 required; preferred 50.' },
  'coa.case.asa.class_i':                             { minRequired: 0,    label: 'ASA Class I', guidance: 'Patient Physical Status Class I: A normal healthy patient. Each patient must have only one physical status. Used only for learning experiences where the student administers an anesthetic. No COA minimum required.' },
  'coa.case.asa.class_ii':                            { minRequired: 0,    label: 'ASA Class II', guidance: 'Patient Physical Status Class II: A patient with mild systemic disease. No COA minimum required.' },
  'coa.case.asa.class_iii_to_vi':                     { minRequired: 200,  recommended: 300, label: 'ASA Classes III–VI (Total)', guidance: 'Patient Physical Status Classes III–VI combined total. Minimum 200 required; preferred 300. Class III: severe systemic disease. Class IV: severe systemic disease that is a constant threat to life. Class V: moribund patient not expected to survive without the operation. Class VI: brain-dead patient for organ donation.' },
  'coa.case.asa.class_iii':                           { minRequired: 50,   recommended: 100, label: 'ASA Class III', guidance: 'Patient Physical Status Class III: A patient with severe systemic disease. Minimum 50 required; preferred 100.' },
  'coa.case.asa.class_iv':                            { minRequired: 10,   recommended: 100, label: 'ASA Class IV', guidance: 'Patient Physical Status Class IV: A patient with severe systemic disease that is a constant threat to life. Minimum 10 required; preferred 100.' },
  'coa.case.asa.class_v':                             { minRequired: 0,    recommended: 5,   label: 'ASA Class V', guidance: 'Patient Physical Status Class V: A moribund patient who is not expected to survive without the operation. No COA minimum; preferred 5.' },
  'coa.case.asa.class_vi':                            { minRequired: 0,    label: 'ASA Class VI', guidance: 'Patient Physical Status Class VI: A brain-dead patient whose organs are being removed for donor purposes. No COA minimum.' },
  'coa.case.age.geriatric_65_plus':                   { minRequired: 100,  recommended: 200, label: 'Geriatric (65+)', guidance: 'Geriatric patients 65 years of age or older. Minimum 100 required; preferred 200.' },
  'coa.case.age.pediatric_total':                     { minRequired: 0,    label: 'Pediatric Cases (Total)', guidance: 'Total pediatric cases. Includes all patients less than 12 years of age. Tracked but no separate COA total minimum — see sub-category minimums.' },
  'coa.case.age.pediatric_2_12':                      { minRequired: 30,   recommended: 75,  label: 'Pediatric (2–12 yr)', guidance: 'Pediatric patients from 2 to 12 years of age. Minimum 30 required; preferred 75.' },
  'coa.case.age.pediatric_lt2':                       { minRequired: 10,   recommended: 25,  label: 'Pediatric (< 2 yr)', guidance: 'Pediatric patients less than 2 years of age. Minimum 10 required; preferred 25.' },
  'coa.case.age.neonate_lt4w':                        { minRequired: 0,    recommended: 5,   label: 'Neonate (< 4 wk)', guidance: 'Neonates less than 4 weeks of age. No COA minimum; preferred 5.' },
  'coa.case.ob.obstetrical_management':               { minRequired: 30,   recommended: 40,  label: 'Obstetrical Management', guidance: 'Students may count clinical experiences in this category only if the procedure being performed is intended to facilitate delivery of the fetus. The COA is aware the number of required cesarean deliveries (10) and analgesia for labor cases (10) do not equal the total number of required Obstetrical Management cases (30). Minimum 30 required; preferred 40.' },
  'coa.case.ob.cesarean_delivery':                    { minRequired: 10,   recommended: 15,  label: 'Cesarean Delivery', guidance: 'When anesthesia is delivered for a cesarean delivery, regardless of whether it is a continuation of a labor epidural, it is counted in this category. The student records the experience as ONE case, for ONE patient. Minimum 10 required; preferred 15.' },
  'coa.case.ob.analgesia_for_labor':                  { minRequired: 10,   recommended: 15,  label: 'Analgesia for Labor', guidance: 'Students performing a pre-anesthetic assessment, developing a plan of care, performing an intervention (e.g., epidural catheter placement), and providing care following the intervention, should count the experience as a SINGLE case and a SINGLE pain management encounter even if the student periodically returns to evaluate the patient and adjust the epidural dosing. Minimum 10 required; preferred 15.' },
  'coa.case.anatomic.intra_abdominal':                { minRequired: 75,   label: 'Anatomic: Intra-abdominal', guidance: 'Abdominal procedures defined as cases where the abdomen is entered via open or laparoscopic procedures. Intra-abdominal cases include total abdominal hysterectomy and radical prostatectomy. ERCP and other intestinal endoscopy cases would NOT be counted as intra-abdominal. Minimum 75 required.' },
  'coa.case.anatomic.intracranial_total':             { minRequired: 5,    recommended: 20,  label: 'Anatomic: Intracranial (Total)', guidance: 'Intracranial procedures defined as cases where a procedure occurs within the brain. Total includes both open and closed intracranial procedures. Minimum 5 required; preferred 20.' },
  'coa.case.anatomic.intracranial_open':              { minRequired: 3,    recommended: 10,  label: 'Anatomic: Intracranial – Open', guidance: 'Open intracranial procedures: the brain is accessed through the skull, or an incision from another anatomical area. Examples: burr hole decompression and intracranial procedures via transphenoidal approach. Minimum 3 required; preferred 10.' },
  'coa.case.anatomic.intracranial_closed':            { minRequired: 0,    recommended: 10,  label: 'Anatomic: Intracranial – Closed', guidance: 'Closed intracranial procedures: the brain is accessed percutaneously via catheter. Examples: gamma knife procedures and percutaneous aneurysm coiling. No COA minimum; preferred 10.' },
  'coa.case.anatomic.oropharyngeal':                  { minRequired: 20,   label: 'Anatomic: Oropharyngeal', guidance: 'Any procedure performed within or via the oral cavity, including the oropharynx. Examples: bronchoscopy (including robotic), esophagoscopy, oral endoscopy (ERCP), oral procedures (orthodontic/dental, tongue, uvea, palate, pharynx, tonsils, adenoids, bony fractures), trans oral cervical spine, odontectomy. Minimum 20 required.' },
  'coa.case.anatomic.intrathoracic_total':            { minRequired: 15,   recommended: 40,  label: 'Anatomic: Intrathoracic (Total)', guidance: 'Intrathoracic procedures defined as a procedure within the thorax where the thorax is surgically open or entered via laparoscope. Total includes heart (open and closed), lung, and other intrathoracic procedures. Minimum 15 required; preferred 40.' },
  'coa.case.anatomic.intrathoracic_open_heart':       { minRequired: 5,    recommended: 10,  label: 'Anatomic: Open Heart (with/without CPB)', guidance: 'Open heart cases include procedures performed with or without cardiopulmonary bypass. With CPB: standard open heart surgery. Without CPB: off-pump coronary artery bypass (OPCAB) and minimally invasive direct coronary artery bypass (MIDCAB). Minimum 5 required; preferred 10.' },
  'coa.case.anatomic.intrathoracic_open_heart_cpb':   { minRequired: 0,    label: 'Anatomic: Open Heart – With CPB', guidance: 'Open heart procedures performed with cardiopulmonary bypass. Standard open heart surgery requiring the heart-lung machine.' },
  'coa.case.anatomic.intrathoracic_open_heart_no_cpb':{ minRequired: 0,    label: 'Anatomic: Open Heart – Without CPB', guidance: 'Open heart procedures performed without cardiopulmonary bypass. Includes off-pump coronary artery bypass (OPCAB) and minimally invasive direct coronary artery bypass (MIDCAB).' },
  'coa.case.anatomic.intrathoracic_closed_heart':     { minRequired: 0,    recommended: 10,  label: 'Anatomic: Closed Heart', guidance: 'Closed heart cases: cardiac ablation, ICD, TAVR, transcatheter pulmonary valve replacement, perivalvular leak closure, percutaneous mitral valve repair, pacemaker lead extraction (lead > 1 yr old), pulmonary artery/vein stent, LAA closure device, and Lariat procedure. NOT appropriate: routine cardiac catheterizations and routine pacemaker insertions. No COA minimum; preferred 10.' },
  'coa.case.anatomic.intrathoracic_lung':             { minRequired: 5,    label: 'Anatomic: Intrathoracic – Lung', guidance: 'Includes procedures on the lung via open thoracotomy and via thoracoscope. Examples: pulmonary artery thrombectomy, VATS involving the lung. Simple insertion of a chest tube to treat pulmonary conditions is NOT counted as an intrathoracic procedure. Minimum 5 required.' },
  'coa.case.anatomic.intrathoracic_other':            { minRequired: 0,    label: 'Anatomic: Intrathoracic – Other', guidance: 'Includes mediastinoscopy; procedures on the esophagus, thymus, and diaphragm; procedures on great vessels including the thoracic aorta (e.g., thoracic aneurysm repair via open thorax or endovascular stent placement) or vena cava.' },
  'coa.case.anatomic.neck':                           { minRequired: 5,    recommended: 10,  label: 'Anatomic: Neck', guidance: 'Neck procedures. Examples: tracheostomy, thyroidectomy, external tracheal revisions, extensive head/neck surgery for cancer/reconstruction. Minimum 5 required; preferred 10.' },
  'coa.case.anatomic.neuroskeletal':                  { minRequired: 20,   label: 'Anatomic: Neuroskeletal', guidance: 'Spine surgery for disc, bone, or nerve repair/intervention including anterior approach performed by neurosurgery or orthopedics. Minimum 20 required.' },
  'coa.case.anatomic.vascular':                       { minRequired: 10,   recommended: 30,  label: 'Anatomic: Vascular', guidance: 'Includes endovascular aortic stents, carotid endarterectomy, and other open or percutaneous procedures performed on vascular structures (bypass, graft placements) including dialysis patients\' establishment or revision of AV fistulas. Minimum 10 required; preferred 30.' },
  'coa.skill.airway.mask_ventilation':                { minRequired: 100,  recommended: 200, label: 'Mask Ventilation', guidance: 'Positive-pressure ventilation administered using a mask during induction and/or maintenance of a case as well as resuscitation events. Students may count all experiences where they provide positive pressure ventilation during induction, maintenance, or emergence, as well as code responses (only 1 mask ventilation experience may be documented per patient). Minimum 100 required; preferred 200.' },
  'coa.skill.airway.mask_ventilation.maintenance':    { minRequired: 25,   label: 'Mask Ventilation – Maintenance', guidance: 'Positive-pressure ventilation via mask during maintenance of a case (not just induction). Example: A student induces general anesthesia using TIVA for a short procedure (ECT, cardioversion). The airway is managed via bag-mask. Minimum 25 required.' },
  'coa.skill.airway.supraglottic_total':              { minRequired: 35,   recommended: 50,  label: 'Supraglottic Airway Devices (Total)', guidance: 'Supraglottic airway devices are placed above the glottis and include laryngeal masks and other devices. Total of LMA and other supraglottic devices combined. Minimum 35 required; preferred 50.' },
  'coa.skill.airway.supraglottic_lma':                { minRequired: 0,    label: 'Supraglottic – LMA', guidance: 'Laryngeal mask airway (LMA) placement. If a student inserts a laryngeal mask and then performs a laryngeal mask-guided endotracheal intubation, this would be recorded in both Supraglottic – LMA AND Tracheal intubation – Oral AND Alternative tracheal intubation – Other techniques.' },
  'coa.skill.airway.supraglottic_other':              { minRequired: 0,    label: 'Supraglottic – Other', guidance: 'Other supraglottic airway devices (not LMA). Includes cuffed oropharyngeal tubes with esophageal cuffs, cuffed oropharyngeal tubes without esophageal cuffs, and cuffless anatomically shaped pharyngeal tubes.' },
  'coa.skill.airway.tracheal_intubation_total':       { minRequired: 250,  label: 'Tracheal Intubation (Total)', guidance: 'Tracheal intubation may only count if the student is SUCCESSFUL at placing the endotracheal tube. Unsuccessful attempts may not be counted. Total includes both oral and nasal intubations. Minimum 250 required.' },
  'coa.skill.airway.tracheal_intubation_oral':        { minRequired: 0,    label: 'Tracheal Intubation – Oral', guidance: 'Oral tracheal intubation. Only successful placements count. A student who performs a direct laryngoscopy and is unable to pass the endotracheal tube, or inadvertently intubates the esophagus, may not count this as a tracheal intubation. Intubations accomplished via alternative techniques should be counted in BOTH tracheal intubation AND the alternative tracheal intubation categories.' },
  'coa.skill.airway.tracheal_intubation_nasal':       { minRequired: 5,    label: 'Tracheal Intubation – Nasal', guidance: 'Nasal tracheal intubation. Only successful placements count. Can be adult or pediatric. Minimum 5 required.' },
  'coa.skill.airway.alt_intubation_total':            { minRequired: 25,   recommended: 50,  simulationAllowed: true, label: 'Alternative Intubation Techniques (Total)', guidance: 'Alternative tracheal intubation techniques include fiberoptic intubation, light wand, retrograde tracheal intubation, transtracheal techniques, gum elastic bougie/tracheal tube changer, LMA guided intubation, cricothyroidotomy, video assisted laryngoscopy, etc. Should be counted in BOTH tracheal intubation AND the alternative tracheal intubation categories. Minimum 25 required; preferred 50.' },
  'coa.skill.airway.alt_intubation_endoscopic_total': { minRequired: 5,    recommended: 15,  simulationAllowed: true, label: 'Endoscopic Techniques (Total)', guidance: 'Airway endoscopy is the skillful manipulation of a flexible endoscopic instrument into the airway cavity. Devices include fiberoptic bronchoscopes, non-fiberoptic bronchoscopes, flexible fiberoptic and non-fiberoptic videoscopes. Minimum 5 required; preferred 15 (partial simulation allowed).' },
  'coa.skill.airway.alt_intubation_endoscopic_actual':{ minRequired: 0,    label: 'Endoscopic – Actual', guidance: 'Actual tracheal tube placement in a human patient using a flexible endoscope. Airway assessment via flexible endoscopic bronchoscopy via an in situ endotracheal or endobronchial tube does NOT count toward the required endoscopic techniques.' },
  'coa.skill.airway.alt_intubation_endoscopic_simulated':{ minRequired: 0, simulationAllowed: true, label: 'Endoscopic – Simulated', guidance: 'Simulated tracheal tube placement using a human patient simulator or task trainer. Simulated experiences may satisfy part, but not all, of the required endoscopic technique experiences.' },
  'coa.skill.airway.alt_intubation_other':            { minRequired: 0,    label: 'Alternative Intubation – Other', guidance: 'Alternative intubation techniques other than endoscopic. The placement of supraglottic airway devices is NOT included here (counted separately). However, if a tracheal tube is advanced into the trachea via the supraglottic airway device, count it here. Examples: light wand, retrograde intubation, transtracheal jet ventilation, bougie, LMA-guided intubation, cricothyroidotomy, video laryngoscopy (GlideScope, McGrath).' },
  'coa.skill.regional.actual_administration_total':   { minRequired: 35,   label: 'Regional – Actual Administration (Total)', guidance: 'As long as students administer no fewer than 10 spinals, 10 epidurals, and 10 peripheral blocks, the remaining 5 additional techniques can be all of one technique or any combination totaling 35. Simulation cannot be used alone to meet the required number of peripheral nerve or neuraxial blocks. Minimum 35 required.' },
  'coa.skill.regional.spinal':                        { minRequired: 10,   recommended: 50,  label: 'Spinal – Actual Administration', guidance: 'Spinal anesthesia – actual administration total. Includes both anesthesia and pain management. Minimum 10 required; preferred 50. A student who performs a combined spinal/epidural catheter placement counts both procedures (spinal AND epidural). Simulation cannot be used alone.' },
  'coa.skill.regional.spinal_anesthesia':             { minRequired: 0,    label: 'Spinal – Anesthesia', guidance: 'Spinal anesthesia administered as the primary anesthetic technique for a surgical procedure. Example: A student administers a spinal anesthetic for cesarean delivery and remains for the management of the case.' },
  'coa.skill.regional.spinal_pain_mgmt':              { minRequired: 0,    label: 'Spinal – Pain Management', guidance: 'Spinal technique used for pain management purposes (not as the primary surgical anesthetic). Example: Intrathecal opioid administration for postoperative pain.' },
  'coa.skill.regional.epidural':                      { minRequired: 10,   recommended: 50,  label: 'Epidural – Actual Administration', guidance: 'Epidural anesthesia/analgesia – actual administration total. Includes both anesthesia and pain management. Minimum 10 required; preferred 50. Simulation cannot be used alone.' },
  'coa.skill.regional.epidural_anesthesia':           { minRequired: 0,    label: 'Epidural – Anesthesia', guidance: 'Epidural technique administered as the primary anesthetic for a surgical procedure. Example: Epidural for a lower extremity vascular procedure.' },
  'coa.skill.regional.epidural_pain_mgmt':            { minRequired: 0,    label: 'Epidural – Pain Management', guidance: 'Epidural technique used for pain management. Example: Epidural catheter for labor analgesia or post-operative pain management.' },
  'coa.skill.regional.peripheral_block':              { minRequired: 10,   recommended: 50,  label: 'Peripheral Block – Actual Administration', guidance: 'Peripheral nerve block – actual administration total. Minimum 10 required; preferred 50. Includes both upper and lower extremity blocks, for both anesthesia and pain management. Simulation may satisfy part of this requirement. Simulation cannot be used alone.' },
  'coa.skill.regional.peripheral_anesthesia_upper':   { minRequired: 0,    label: 'Peripheral Block – Anesthesia, Upper Extremity', guidance: 'Peripheral nerve block – upper extremity anesthesia. Also counts toward the peripheral block actual administration total (min 10). Examples: interscalene, supraclavicular, infraclavicular, axillary, wrist blocks for upper extremity procedures.' },
  'coa.skill.regional.peripheral_anesthesia_lower':   { minRequired: 0,    label: 'Peripheral Block – Anesthesia, Lower Extremity', guidance: 'Peripheral nerve block – lower extremity anesthesia. Also counts toward the peripheral block actual administration total (min 10). Examples: femoral, popliteal sciatic, adductor canal, ankle blocks for lower extremity procedures.' },
  'coa.skill.regional.peripheral_anesthesia':         { minRequired: 0,    label: 'Peripheral Block – Anesthesia', guidance: 'Peripheral nerve block administered as the primary anesthetic technique for a surgical procedure.' },
  'coa.skill.regional.peripheral_pain_mgmt':          { minRequired: 0,    label: 'Peripheral Block – Pain Management', guidance: 'Peripheral nerve block used for pain management (post-operative analgesia, not primary anesthetic technique).' },
  'coa.skill.regional.peripheral_pain_mgmt_upper':    { minRequired: 0,    label: 'Peripheral Block – Pain Mgmt, Upper Extremity', guidance: 'Peripheral nerve block for pain management – upper extremity. Example: Interscalene or supraclavicular catheter for post-operative shoulder or arm pain.' },
  'coa.skill.regional.peripheral_pain_mgmt_lower':    { minRequired: 0,    label: 'Peripheral Block – Pain Mgmt, Lower Extremity', guidance: 'Peripheral nerve block for pain management – lower extremity. Example: Femoral nerve catheter or adductor canal block for post-operative knee or lower leg pain.' },
  'coa.skill.regional.other_total':                   { minRequired: 0,    label: 'Regional Other Techniques (Total)', guidance: 'Other regional techniques not classified as spinal, epidural, or peripheral nerve block. Examples (COA footnote 6): truncal, cutaneous, head, and neck blocks (e.g., transversus abdominis plane [TAP], rectus sheath, ilioinguinal, iliohypogastric, oral, and maxillofacial blocks).' },
  'coa.skill.regional.other_anesthesia':              { minRequired: 0,    label: 'Regional Other – Anesthesia', guidance: 'Other regional techniques – used for surgical anesthesia. Examples: TAP block as the primary anesthetic for hernia repair, paravertebral block for thoracotomy.' },
  'coa.skill.regional.other_pain_mgmt':               { minRequired: 0,    label: 'Regional Other – Pain Management', guidance: 'Other regional techniques – used for pain management. Examples: TAP block for postoperative abdominal pain, iliohypogastric block for inguinal hernia post-op.' },
  'coa.skill.regional.management_total':              { minRequired: 35,   recommended: 50,  label: 'Regional Management (Total)', guidance: 'The student manages a patient under a regional anesthetic that was placed (by the student or another provider). Total of anesthesia and pain management. Minimum 35 required; preferred 50.' },
  'coa.skill.regional.management_anesthesia':         { minRequired: 0,    label: 'Regional Management – Anesthesia', guidance: 'Management of a patient receiving regional anesthesia as the primary anesthetic technique for a surgical procedure. Example: Managing a patient\'s spinal anesthetic for cesarean delivery throughout the case.' },
  'coa.skill.regional.management_pain_mgmt':          { minRequired: 0,    label: 'Regional Management – Pain Management', guidance: 'Management of a regional technique used for pain management. Example: Managing a labor epidural, adjusting dosing, assessing effectiveness throughout the patient\'s labor.' },
  'coa.skill.arterial.line_placement':                { minRequired: 25,   label: 'Arterial Line Placement', guidance: 'Arterial puncture/catheter insertion. If you puncture the artery and successfully obtain a blood gas sample, this does count. If you puncture an artery in an attempt to place an arterial catheter but are unsuccessful, this does NOT count. Simulation cannot be used to meet this category. Minimum 25 required.' },
  'coa.skill.arterial.monitoring':                    { minRequired: 30,   label: 'Intra-arterial Monitoring', guidance: 'Intra-arterial blood pressure monitoring. Used anytime an arterial catheter is used to monitor arterial waveforms and other clinical variables. May include standard arterial lines as well as newer technologies such as FloTrac® Hemosphere, VolumeView® sensor, LiDCO®plus, and PiCCO®. Minimum 30 required.' },
  'coa.skill.cvc.nonpicc_placement':                  { minRequired: 10,   recommended: 15,  simulationAllowed: true, label: 'CVC Placement (Non-PICC)', guidance: 'Central venous catheter placement (non-PICC). The placement of an introducer qualifies as a CVC insertion. The student should perform the procedure including insertion and directing of the needle. Assistance can be provided, but the procedure must be performed by the student. Minimum 10 required; preferred 15 (5 actual minimum, remainder may be simulated).' },
  'coa.skill.cvc.nonpicc_actual':                     { minRequired: 5,    label: 'CVC – Actual', guidance: 'CVC placement (non-PICC) – actual patient. If the student also floats a pulmonary artery catheter, count it as both a CVC insertion and a PAC insertion. Minimum 5 actual required.' },
  'coa.skill.cvc.nonpicc_simulated':                  { minRequired: 0,    simulationAllowed: true, label: 'CVC – Simulated', guidance: 'CVC placement (non-PICC) – simulated. Simple models and simulated experiences may be used to satisfy part of this requirement.' },
  'coa.skill.cvc.monitoring':                         { minRequired: 10,   recommended: 15,  label: 'CVC Monitoring', guidance: 'Used anytime a CVC is used to monitor central venous waveforms and other clinical variables. Monitoring right atrial pressure with a pulmonary artery catheter is counted under PAC monitoring, NOT here. Minimum 10 required; preferred 15.' },
  'coa.skill.picc.placement':                         { minRequired: 0,    simulationAllowed: true, label: 'PICC Placement', guidance: 'PICC (Peripherally Inserted Central Catheter) placement. Insertion of a PICC does NOT meet the requirement for CVC placement – these are separate categories.' },
  'coa.skill.picc.actual':                            { minRequired: 0,    label: 'PICC – Actual', guidance: 'PICC placement performed on an actual patient.' },
  'coa.skill.picc.simulated':                         { minRequired: 0,    simulationAllowed: true, label: 'PICC – Simulated', guidance: 'PICC placement performed in a simulation environment.' },
  'coa.skill.pac.placement':                          { minRequired: 0,    recommended: 5,   label: 'PA Catheter Placement', guidance: 'Pulmonary artery catheter placement. No COA minimum; preferred 5. If the student floats a PAC after placing a CVC introducer, count both a CVC insertion AND a PAC insertion.' },
  'coa.skill.pac.monitoring':                         { minRequired: 0,    recommended: 10,  label: 'PA Catheter Monitoring', guidance: 'Pulmonary artery catheter monitoring. Monitoring right atrial pressure with a PAC is counted here, not under CVC monitoring. No COA minimum; preferred 10.' },
  'coa.skill.iv.placement':                           { minRequired: 100,  label: 'Peripheral IV Placement', guidance: 'Intravenous catheter placement. If an intravenous catheter is placed using ultrasound, the procedure would be counted in this category AND also in Ultrasound-guided techniques – Vascular. Minimum 100 required.' },
  'coa.skill.advanced_hemodynamic_monitoring':        { minRequired: 0,    label: 'Advanced Hemodynamic Monitoring', guidance: 'Advanced minimally- and non-invasive hemodynamic monitoring. May include but is not limited to FloTrac®, ClearSight®, Esophageal Doppler, PiCCO®, and LiDCO®.' },
  'coa.skill.ultrasound.guided_total':                { minRequired: 20,   simulationAllowed: true, label: 'Ultrasound-Guided Techniques (Total)', guidance: 'Ultrasound-guided techniques total. Includes both regional and vascular applications. Minimum 20 required.' },
  'coa.skill.ultrasound.guided_regional':             { minRequired: 10,   simulationAllowed: true, label: 'US-Guided Regional (Total)', guidance: 'Ultrasound-guided regional techniques. Regional includes neuraxial, truncal, and peripheral nerve blocks. No clinical experience can be obtained by simulation alone. Minimum 10 required.' },
  'coa.skill.ultrasound.guided_regional_actual':      { minRequired: 0,    label: 'US-Guided Regional – Actual', guidance: 'Ultrasound-guided regional performed on actual patients. Neuraxial, truncal, and peripheral nerve blocks using ultrasound guidance.' },
  'coa.skill.ultrasound.guided_regional_simulated':   { minRequired: 0,    simulationAllowed: true, label: 'US-Guided Regional – Simulated', guidance: 'Ultrasound-guided regional – simulated. Simulation may satisfy part of this requirement. No clinical experience can be obtained by simulation alone.' },
  'coa.skill.ultrasound.guided_vascular':             { minRequired: 10,   simulationAllowed: true, label: 'US-Guided Vascular (Total)', guidance: 'Ultrasound-guided vascular techniques. Includes arterial, CVC, PICC, and peripheral IV access. No clinical experience can be obtained by simulation alone. Minimum 10 required.' },
  'coa.skill.ultrasound.guided_vascular_actual':      { minRequired: 0,    label: 'US-Guided Vascular – Actual', guidance: 'Ultrasound-guided vascular performed on actual patients. Note: PIV placed with ultrasound counts in both IV placement AND ultrasound-guided vascular.' },
  'coa.skill.ultrasound.guided_vascular_simulated':   { minRequired: 0,    simulationAllowed: true, label: 'US-Guided Vascular – Simulated', guidance: 'Ultrasound-guided vascular – simulated. Simulation may satisfy part of this requirement.' },
  'coa.skill.pocus':                                  { minRequired: 0,    simulationAllowed: true, label: 'POCUS (Total)', guidance: 'Point of Care Ultrasound refers to the use of portable ultrasonography at a patient\'s bedside for ASSESSMENT purposes. This EXCLUDES the use of ultrasound for image-guidance purposes such as regional anesthesia or vascular access. Examples: assessing cardiac function, pulmonary function, gastric volume, and/or airway anatomy preoperatively. Includes transesophageal, transthoracic, or subxiphoid ultrasound to assess fluid status and/or cardiac function.' },
  'coa.skill.pocus.actual':                           { minRequired: 0,    label: 'POCUS – Actual', guidance: 'POCUS performed on actual patients for clinical assessment.' },
  'coa.skill.pocus.simulated':                        { minRequired: 0,    simulationAllowed: true, label: 'POCUS – Simulated', guidance: 'POCUS performed in a simulation environment.' },
  'coa.skill.acls':                                   { minRequired: 0,    label: 'ACLS', guidance: 'Advanced Cardiovascular Life Support (ACLS) certification. Current certification required.' },
  'coa.skill.pals':                                   { minRequired: 0,    label: 'PALS', guidance: 'Pediatric Advanced Life Support (PALS) certification. Current certification required.' },

  // ── Participation types (no minRequired — informational only) ─────────────
  'participation': { minRequired: 0, label: 'Participation Type', guidance: 'Primary: Student directly administers the anesthetic and is credited for the full case. Shared: Two students share anesthetic management for a single patient; each student receives credit for one case. Relief: Student relieves another anesthesia provider. A relief experience is documented as a case ONLY when a significant anesthetic event occurs during the relief period (e.g., induction, emergence, airway difficulty, hemodynamic instability). Observe / Chart-Only: The student does NOT provide anesthesia care and may NOT count the case toward any COA requirement. Observational experiences do not count toward case totals.' },
};

/** Returns a human-readable label for a requirement key, falling back to the raw key. */
export function coaLabel(key: string): string {
  return COA_META[key]?.label ?? key;
}

/** Returns the interpretive guidance text for a requirement key, or undefined if none. */
export function coaGuidance(key: string): string | undefined {
  return COA_META[key]?.guidance;
}

/** Returns the COA minimum required count (0 = tracked only, no enforced minimum). */
export function coaMinRequired(key: string): number {
  return COA_META[key]?.minRequired ?? 0;
}

/**
 * Returns the COA recommended/preferred target for a requirement key.
 * Returns undefined if no recommended target is set.
 */
export function coaRecommended(key: string): number | undefined {
  return COA_META[key]?.recommended;
}
